### ISSUE TITLE
Screen does not refresh automatically

### ISSUE THREAD

**Issue by Attwood-Wayne** [wittsend/AEL-JL#15]
Job List has to be manually updated using the Refresh button.

**Comment by wittsend** [comment]
All tables should refresh once every minute. Is it only the "All jobs" list not refreshing once every minute?

**Comment by Attwood-Wayne** [comment]
No tables refresh automatically, furthermore if you do refresh manually then only the table that you are on refreshes. Each table must be refreshed manually. I have monitored this today - after making changes on the Job List on one PC, even after 1 hour the v1.2 Job List had not refreshed.

**Comment by Attwood-Wayne** [comment]
Problem resolved - Job List is now refreshing automatically and working much better. Thanks.

**Comment by wittsend** [comment]
There may be some lag with the current release, which is fixed in the next release.
