### ISSUE TITLE
Time elapsed does not take open timesheet entries into account for live data

### ISSUE THREAD

**Issue by Attwood-Wayne** [wittsend/AEL-JL#16]
Time elapsed only shows running total of posted time entries, it no longer runs live as per v1.0

**Comment by wittsend** [comment]
Do you think you could make a copy of the database file for me while there are live timesheet entries active and past it in the Job List workshop job folder? You need to make sure that the modified date and time on the FDB file is recent (Firebird handles the database mostly in RAM and only periodically writes back to the database file to save on disk IO and improve performance). I was not able to test this as I did not have a database with unposted timesheets.

**Comment by Attwood-Wayne** [comment]
Ostendo.FDB has been copied into the "0. Workshop Jobs\Job List Software" folder (dated 8/8/21). I put a copy into the folder on Friday but it was for 6/8/21 at 7.34am - this would not have had any open timesheets on Ostendo. I have kept all of Friday's timesheets open until there was a new FDB file to copy, so the 8/8/21 copy will have plenty of open entries.

**Comment by wittsend** [comment]
Thanks Wayne. I intend to get the new issues sorted this week

**Comment by Attwood-Wayne** [comment]
Thanks very much Matt, appreciating all your efforts. We will continue with Steve and Chris testing v1.2 this week.

**Comment by wittsend** [comment]
I think I've gotten to the bottom of this. Should have it fixed by the end of today.

**Comment by wittsend** [comment]
Should be resolved. Please find updated executable for testing at Y:\...\0. Workshop Jobs\Job List Software\AEL Job List v1\AEL Job List v1\bin\Debug\AEL Job List.exe

**Comment by Attwood-Wayne** [comment]
Live Data is a take. Great work - this is now working correctly.
Thanks for also sorting out the lag in yesterdays version. I loaded up the new version yesterday to trial it as well as Chris and Steve. The lag was very noticeable.
The 3 of us have all loaded the latest version this morning and have given the system a good test today. It is working extremely well. It is very nice to use - much smoother, more responsive and appears to be very stable. Both Steve and I love the persistence feature, it makes so much difference. We are all really pleased with the result.
We will continue beta testing into next week and see if there are any other bugs that need attention.

**Comment by wittsend** [comment]
I'm pleased to hear that. I was curious to see how the performance was going to be with some of the changes. The lag would have been much more noticeable for you than Chris and Steve due to the number of tabs you have open. Basically I had inadvertently altered something that meant when the auto refresh started working again it was doing all the SQL queries on the main thread, which is a bit of a no no.  All sorted now though. If there are anymore issues then you know what to do, otherwise just let me know when you're ready to publish :)
